### ISSUE TITLE
plugin is installed, but it doesn't show up in System/Configuration

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog-plugin-threatintel#1]
After installation the plugin showed up in the node settings as installed, but not in the System/Configuration Menu.

Since i have to config it to work properly its not usable at the moment.

Graylog 2.1.1

Thanks

**Comment by mmogilko** [comment]
Hi! Same problem. I can't figure out how to turn it on.
server.log:
[OTXLookupProvider] OTX domain lookup requested but OTX is not enabled in configuration. Please enable it first.
The relevant options is not available in WUI System/Configurations ->Configurations
Thanks!

**Comment by gruselglatz** [comment]
I've tried it to enable the Plugin via the API, but there is also no configClass registered.

**Comment by omercnet** [comment]
same issue here
Graylog server 2.1.1+01d50e5

**Comment by jpferrero** [comment]
same to me...
Graylog 2.1.1+01d50e5

**Comment by lennartkoopmann** [comment]
I'm looking into this. Note that is plugin is not officially finished yet. :)

**Comment by lennartkoopmann** [comment]
fixed in efb8fcc4ddcb612b41444dc55c0f3553676eea4e

**Comment by lennartkoopmann** [comment]
Fixed in v0.5.0 and now available for download: https://github.com/Graylog2/graylog-plugin-threatintel/releases/tag/0.5.0

**Comment by omercnet** [comment]
@lennartkoopmann upgraded to 0.7.1-SNAPSHOT and still not seeing anything in Configurations

```
2016-10-31 13:52:03,456 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Threat Intelligence Plugin 0.7.1-SNAPSHOT [org.graylog.plugins.threatintel.ThreatIntelPlugin]
2016-10-31 13:52:11,054 INFO : org.graylog.plugins.threatintel.providers.tor.TorExitNodeLookupProvider - Refreshing internal table of known Tor exit nodes.
2016-10-31 13:52:12,423 INFO : org.graylog.plugins.threatintel.providers.spamhaus.SpamhausIpLookupProvider - Refreshing internal table of Spamhaus drop list IPs.


```

**Comment by illukas** [comment]
Installing from .deb package of version 0.10.0 to Graylog 2.3.0 makes this issue reappear.

**Comment by joschi** [comment]
@illukas The Threat Intelligence plugin 0.10.0 is not compatible with Graylog 2.3.x.

There is currently no version of this plugin which is compatible with Graylog 2.3.x.
The next release will be with Graylog 2.4.0.

**Comment by illukas** [comment]
Would it be possible to get an alpha release of the compatible plugin on github?

**Comment by joschi** [comment]
@illukas We plan to release Graylog 2.4.0-beta.1 including this plugin soon.

There won't be a version for Graylog 2.3.x.
